export enum ErrorMessage {
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_API_KEY = 'INVALID_API_KEY',
  NOT_FOUND = 'NOT_FOUND',
  SUCCESS = 'SUCCESS',
  ACCESS_DENIED = 'ACCESS_DENIED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
  MAX_PRODUCTS_FREEMIUM = 'MAX_PRODUCTS_FREEMIUM',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
}
