export enum HttpMessage {
  USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_API_KEY = 'INVALID_API_KEY',
  NOT_FOUND = 'NOT_FOUND',
  SUCCESS = 'SUCCESS',
  ACCESS_DENIED = 'ACCESS_DENIED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
}
